kind: Cluster
name: not-imrank
talos:
  version: v1.6.7
kubernetes:
  version: 1.29.3
features:
  enableWorkloadProxy: true
  backupConfiguration:
    interval: 1h
patches:
  - name: kube-span
    file: patches/kube-span.yaml
  - name: cni
    file: patches/cni.yaml
---
kind: ControlPlane
machines:
  - da8b3c42-a355-6313-23d3-cd50882a3b4c
patches:
  - name: cilium
    file: patches/cilium.yaml
  - name: monitoring
    file: patches/monitoring.yaml
  - name: argocd
    file: patches/argocd.yaml
---
kind: Workers
name: workers
machines:
  - f69f3c42-d744-83da-b7bf-d248d41084f3
  - 7fd23c42-25d1-f419-ee6a-f682fe5b2bf2
  - 6dbd3c42-6daf-fe45-1731-18f295044ca2
  - 88873c42-0868-4ce4-ed8d-477dbca3f8c4
