apiVersion: v1
kind: Service
metadata:
  name: argocd-server
  annotations:
    # Enable Omni Workload Proxying for this service
    omni-kube-service-exposer.sidero.dev/port: "50083"
    omni-kube-service-exposer.sidero.dev/label: ArgoCD
